// WARNING: Do NOT edit the input and output ports in this file in a text
// editor if you plan to continue editing the block that represents it in
// the Block Editor! File corruption is VERY likely to occur.

// Copyright (C) 1991-2005 Altera Corporation
// Any  megafunction  design,  and related netlist (encrypted  or  decrypted),
// support information,  device programming or simulation file,  and any other
// associated  documentation or information  provided by  Altera  or a partner
// under  Altera's   Megafunction   Partnership   Program  may  be  used  only
// to program  PLD  devices (but not masked  PLD  devices) from  Altera.   Any
// other  use  of such  megafunction  design,  netlist,  support  information,
// device programming or simulation file,  or any other  related documentation
// or information  is prohibited  for  any  other purpose,  including, but not
// limited to  modification,  reverse engineering,  de-compiling, or use  with
// any other  silicon devices,  unless such use is  explicitly  licensed under
// a separate agreement with  Altera  or a megafunction partner.  Title to the
// intellectual property,  including patents,  copyrights,  trademarks,  trade
// secrets,  or maskworks,  embodied in any such megafunction design, netlist,
// support  information,  device programming or simulation file,  or any other
// related documentation or information provided by  Altera  or a megafunction
// partner, remains with Altera, the megafunction partner, or their respective
// licensors. No other licenses, including any licenses needed under any third
// party's intellectual property, are provided herein.


// Generated by Quartus II Version 4.2 (Build Build 178 01/19/2005)
// Created on Mon Apr 11 11:24:08 2005

//  Module Declaration
module sync_state
(
	// {{ALTERA_ARGS_BEGIN}} DO NOT REMOVE THIS LINE!
	clk, reset, end_line, width, debugcount
	// {{ALTERA_ARGS_END}} DO NOT REMOVE THIS LINE!
);
// Port Declaration

	// {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
	input clk;
	input reset;
	input end_line;
	output [9:0] width;
	output [10:0] debugcount;
	// {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!

	reg [10:0] count;
	reg [9:0] widthreg;

assign width=widthreg;

always @ (posedge clk)
  begin
    if (reset)
    begin
      count<=11'd1000;
    end
    else
    if (end_line) 
    begin
      if (count<11'd1249) count<=count+11'd1; 
      else count<=11'd0;
    end
 end

always 
begin
  if (count<5) widthreg<=273;
  else
  if (count<10) widthreg<=23;
  else
  if (count<620) 
  begin 
    if (count[0]==1) widthreg<=0; 
    else widthreg<=47; 
  end
  else
  if (count<625) widthreg<=23;
  else
  if (count<630) widthreg<=273;
  else
  if (count<635) widthreg<=23;
  else 
  if (count<1245) 
  begin 
    if (count[0]==1) widthreg<=0; 
    else widthreg<=47; 
  end
  else
  widthreg<=23;

end
endmodule
